blank_issues_enabled: false
contact_links:
  - name: ğŸ“š The project documentation
    url: https://arkscript-lang.dev/impl/
    about: Not sure where to look? Check out the documentation first!
  - name: ğŸ’¬ Discussions
    url: https://github.com/orgs/ArkScript-lang/discussions
    about: In case you're unsure your question is a bug, or your feature request needs refining before opening an issue, open a new discussion!
  - name: âœ¨ ArkScript standard library issue tracker
    url: https://github.com/ArkScript-lang/std/issues
    about: Issues related to the standard library should go on the corresponding issue tracker
  - name: âš™ï¸ ArkScript modules issue tracker
    url: https://github.com/ArkScript-lang/modules/issues
    about: Issues related to the modules should go on the corresponding issue tracker
